### ISSUE TITLE
Increase pixel price to 0.000001

### ISSUE THREAD

**Issue by guifel** [liquidity-network/finney.place#7]
Useful tool: https://etherconverter.online

**Comment by guifel** [comment]
Is it deployed? I still see the price in 1 wei.

Also, don't forget to update the front-end, the price should be displayed in Ether:
![Selection_402](https://user-images.githubusercontent.com/15947729/57625234-bd6a1880-7593-11e9-923d-57574bca5784.png)

**Comment by HazemElAgaty** [comment]
@guifel I need it to be merged before deploying. I will change the pixel price to ether okay.

**Comment by HazemElAgaty** [comment]
@guifel 

> Why did you add a single env variable in wei for the price of a pixel?

 I don't get the question. Would you please elaborate?

**Comment by guifel** [comment]
Merged. 
The Pixel price is defined in 2 different files. Ideally, it should be in one place. The best would to have it as an environment variable like for the nocust contract address.
